package com.wallets.api.base.web;

public interface ApiExceptionsConsts {

    // BadRequestException 400

    String INCORRECT_OPERATION_TYPE = "INCORRECT_OPERATION_TYPE";
    String INCORRECT_AMOUNT = "INCORRECT_AMOUNT";

    String CODE_IS_EMPTY = "CODE_IS_EMPTY";
    String EMAIL_IS_EMPTY = "EMAIL_IS_EMPTY";
    String PASSWORD_IS_EMPTY = "PASSWORD_IS_EMPTY";
    String NEW_PASSWORD_IS_EMPTY = "NEW_PASSWORD_IS_EMPTY";
    String TITLE_IS_EMPTY = "TITLE_IS_EMPTY";
    String LAYER_ID_IS_EMPTY = "LAYER_ID_IS_EMPTY";
    String MODEL_FILE_IS_EMPTY = "MODEL_FILE_IS_EMPTY";
    String TYPE_IS_EMPTY = "TYPE_IS_EMPTY";
    String COMMENT_TEXT_IS_EMPTY = "COMMENT_TEXT_IS_EMPTY";
    String FILE_SIZE_TOO_LARGE = "FILE_SIZE_TOO_LARGE";
    String IMAGE_SIZE_TOO_LARGE = "IMAGE_SIZE_TOO_LARGE";
    String VIDEO_SIZE_TOO_LARGE = "VIDEO_SIZE_TOO_LARGE";
    String MODEL_SIZE_TOO_LARGE = "MODEL_SIZE_TOO_LARGE";
    String PAGE_SIZE_TOO_LARGE = "PAGE_SIZE_TOO_LARGE";
    String WIDTH_TOO_LARGE = "WIDTH_TOO_LARGE";
    String WIDTH_TOO_SMALL = "WIDTH_TOO_SMALL";
    String NUMBER_FILES_EXCEEDED = "NUMBER_FILES_EXCEEDED";
    String NOT_VALID_ADDRESS = "NOT_VALID_ADDRESS";

    String INCORRECT_NAME_SYSTEM = "INCORRECT_NAME_SYSTEM";
    String INCORRECT_SYMBOL_NICKNAME = "INCORRECT_SYMBOL_NICKNAME";
    String INCORRECT_NAME_STATUS = "INCORRECT_NAME_STATUS";
    String INCORRECT_NAME_VISIBILITY_STATUS = "INCORRECT_NAME_VISIBILITY_STATUS";
    String INCORRECT_NAME_PRIVACY_STATUS = "INCORRECT_NAME_PRIVACY_STATUS";
    String INCORRECT_NAME_CONDITION = "INCORRECT_NAME_CONDITION";
    String INCORRECT_NAME_ROLE = "INCORRECT_NAME_ROLE";
    String INCORRECT_VALUE_SIZE = "INCORRECT_VALUE_SIZE";
    String INCORRECT_IMAGE_TYPE = "INCORRECT_IMAGE_TYPE";
    String INCORRECT_VIDEO_TYPE = "INCORRECT_VIDEO_TYPE";
    String INCORRECT_MIME_TYPE = "INCORRECT_MIME_TYPE";
    String INCORRECT_PAGE_SIZE = "INCORRECT_PAGE_SIZE";
    String INCORRECT_PAGE_NUM = "INCORRECT_PAGE_NUM";
    String INCORRECT_POST_TYPE = "INCORRECT_POST_TYPE";
    String INCORRECT_MODEL_TYPE = "INCORRECT_MODEL_TYPE";

    // NotAuthorizedException 401

    String BAD_CREDENTIALS = "BAD_CREDENTIALS";
    String NOT_AUTHORIZED = "NOT_AUTHORIZED";
    String NOT_VERIFIED = "NOT_VERIFIED";

    // ForbiddenException 403

    String NO_PERMISSION = "NO_PERMISSION";
    String NOT_EMAIL_PROVIDER = "NOT_EMAIL_PROVIDER";

    // NotFoundException 404

    String WALLET_NOT_FOUND = "WALLET_NOT_FOUND";

    // NotAcceptableException 406

    String INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS";
    String USER_NOT_ACTIVE = "USER_NOT_ACTIVE";
    String USER_DELETED = "USER_DELETED";
    String USER_NOT_DELETED = "USER_NOT_DELETED";
    String NEW_OWNER_NOT_ACTIVE = "NEW_OWNER_NOT_ACTIVE";
    String NOT_YOUR_OBJECT = "NOT_YOUR_OBJECT";
    String NOT_YOUR_AR_OBJECT = "NOT_YOUR_AR_OBJECT";
    String NOT_YOUR_ANCHOR = "NOT_YOUR_ANCHOR";
    String NOT_YOUR_SPACE = "NOT_YOUR_SPACE";
    String NOT_YOUR_LAYER = "NOT_YOUR_LAYER";
    String NOT_YOUR_POST = "NOT_YOUR_POST";
    String NOT_YOUR_QUOTE = "NOT_YOUR_QUOTE";
    String NOT_YOUR_TRANSFER = "NOT_YOUR_TRANSFER";
    String NOT_YOUR_INVITE = "NOT_YOUR_INVITE";
    String NOT_YOUR_REQUEST = "NOT_YOUR_REQUEST";
    String NOT_INVITE_FOR_YOU = "NOT_INVITE_FOR_YOU";
    String NOT_REQUEST_FOR_YOU = "NOT_REQUEST_FOR_YOU";

    String AR_OBJECT_NOT_IN_LAYER = "AR_OBJECT_NOT_IN_LAYER";
    String AR_OBJECT_NOT_IN_SPACE = "AR_OBJECT_NOT_IN_SPACE";

    String USER_NOT_IN_SPACE = "USER_NOT_IN_SPACE";
    String OBJECT_NOT_IN_FAVORITES = "OBJECT_NOT_IN_FAVORITES";
    String AR_OBJECT_IN_ONLY_ONE_SPACE = "AR_OBJECT_IN_ONLY_ONE_SPACE";
    String OBJECT_ON_MODERATION = "OBJECT_ON_MODERATION";
    String OBJECT_NOT_APPROVED = "OBJECT_NOT_APPROVED";
    String OBJECT_NOT_PUBLISHED = "OBJECT_NOT_PUBLISHED";
    String OBJECT_NOT_PUBLIC = "OBJECT_NOT_PUBLIC";
    String OBJECT_IS_PUBLISHED = "OBJECT_IS_PUBLISHED";
    String POST_IS_NOT_QUOTE = "POST_IS_NOT_QUOTE";
    String SPACE_IS_EMPTY = "SPACE_IS_EMPTY";
    String AVATAR_IS_EMPTY = "AVATAR_IS_EMPTY";
    String SPACE_IS_NOT_EMPTY = "SPACE_IS_NOT_EMPTY";

    String NUMBER_OF_LINKS_EXCEEDED = "NUMBER_OF_LINKS_EXCEEDED";
    String REQUEST_ALREADY_ACCEPTED = "REQUEST_ALREADY_ACCEPTED";
    String INVITE_ALREADY_ACCEPTED = "INVITE_ALREADY_ACCEPTED";
    String INVITE_REQUEST_ALREADY_ACCEPTED = "INVITE_REQUEST_ALREADY_ACCEPTED";
    String JSON_PROCESSING_EXCEPTION = "JSON_PROCESSING_EXCEPTION";

    String IT_IS_YOUR_POST = "IT_IS_YOUR_POST";
    String IT_IS_YOUR_SPACE = "IT_IS_YOUR_SPACE";
    String IT_IS_YOU = "IT_IS_YOU";

    // AlreadyExistsException 409

    String EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS";
    String NICKNAME_ALREADY_EXISTS  = "NICKNAME_ALREADY_EXISTS";
    String SUBSCRIBE_ALREADY_EXIST = "SUBSCRIBE_ALREADY_EXIST";
    String ANCHOR_ALREADY_EXIST = "ANCHOR_ALREADY_EXIST";
    String REPOST_ALREADY_EXIST = "REPOST_ALREADY_EXIST";
    String QUOTE_ALREADY_EXIST = "QUOTE_ALREADY_EXIST";

    String AR_OBJECT_ALREADY_IN_SPACE = "AR_OBJECT_ALREADY_IN_SPACE";
    String AR_OBJECT_ALREADY_IN_LAYER = "AR_OBJECT_ALREADY_IN_LAYER";
    String OBJECT_ALREADY_IN_FAVORITES = "OBJECT_ALREADY_IN_FAVORITES";
    String AR_OBJECT_ALREADY_TRANSFER = "AR_OBJECT_ALREADY_TRANSFER";
    String OBJECT_ALREADY_ON_MODERATION = "OBJECT_ALREADY_ON_MODERATION";
    String GLB_MODEL_ALREADY_EXIST = "GLB_MODEL_ALREADY_EXIST";
    String USDZ_MODEL_ALREADY_EXIST = "USDZ_MODEL_ALREADY_EXIST";

    String TRANSFER_ALREADY_EXIST = "TRANSFER_ALREADY_EXIST";
    String CODE_ALREADY_SENT = "CODE_ALREADY_SENT";
    String USER_ALREADY_IN_SPACE = "USER_ALREADY_IN_SPACE";
    String USER_ALREADY_INVITED = "USER_ALREADY_INVITED";
    String USER_ALREADY_REQUESTED = "USER_ALREADY_REQUESTED";

    //ServiceUnavailableException 503

    String ERROR_UPLOADING_FILE = "ERROR_UPLOADING_FILE";
    String ERROR_DOWNLOADING_FILE = "ERROR_DOWNLOADING_FILE";
    String ERROR_DELETING_FILE = "ERROR_DELETING_FILE";
    String ERROR_SENDING_MESSAGE = "ERROR_SENDING_MESSAGE";
}
